service: simple-http-fluent

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10

functions:
  greeting:
    handler: handler.greeting
    events:
      - http:
          path: greet
          method: get

  personalGreeting:
    handler: handler.personalGreeting
    events:
      - http:
          path: greet
          method: post
          cors: true
